#!/bin/ksh

daemon="/var/www/_mastodon/.rbenv/shims/bundle exec puma -C config/puma.rb"
datadir="/var/www/_mastodon/live"
env="RAILS_ENV=production PORT=3000"

rc_pre() {
	${env} ${daemon}
}

rc_reload=NO
rc_bg=YES
rc_cmd $1
